name = "mobile-learning-platform"
compatibility_date = "2023-05-11"
compatibility_flags = ["nodejs_compat"]
main = "dist/index.js"

[build]
command = "npm run build"

[site]
bucket = "./dist/public"

[env.production]
workers_dev = false

[dev]
port = 8787
