name = "skrolla"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = "_worker.js"

[build]
command = "npm install && npm run build"

[site]
bucket = "./dist/public"

[observability.logs]
enabled = true

[env.production]
name = "skrolla-production"

[env.development]
name = "skrolla-development" 