name = "skrolla"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = "_worker.js"

[build]
command = "npm run build:frontend"

[site]
bucket = "./dist/public"

# Cache settings for better performance
[site.cache]
caching = true
browser_ttl = 3600
serve_stale = true

# Enable Web Optimization features for better performance
[optimization]
bundle = true    # Bundle your JavaScript
minify = true    # Minify your JavaScript

[observability.logs]
enabled = true

[env.production]
name = "skrolla-production"

[env.development]
name = "skrolla-development"